"""introduce empty instances table

Revision ID: 42
Revises: 41
Create Date: 2026-05-07 15:51:17.510641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42'
down_revision = '41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forge_instance',
    sa.Column('id', sa.Integer(), nullable=False, comment='Internal unique identifier for this forge instance'),
    sa.Column('platform_type', sa.Integer(), nullable=False, comment='Type specifier identifying the relevant platform API interface to CollectOSS'),
    sa.Column('name', sa.String(), nullable=False, comment='User-specified name for this forge instance'),
    sa.Column('date_added', sa.DateTime(timezone=True), nullable=False),
    sa.Column('domain_name', sa.String(), nullable=False, comment='The base domain name (without the scheme) where this instance is hosted'),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='denotes whether collection should run for this instance'),
    sa.PrimaryKeyConstraint('id'),
    schema='augur_operations'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forge_instance', schema='augur_operations')
    # ### end Alembic commands ###
